# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
NODE_COUNT = 4

INTNET_NAME = [*('A'..'Z')].sample(8).join

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  NODE_COUNT.times do |i|
    node_id = "node#{i}"
    
    config.vm.define node_id do |node|
      node.vm.box_url = "http://www.krishnaraman.net/downloads/f19.box"
      node.vm.box = "fedora19"
      node.vm.hostname = "#{node_id}.intranet.local"
      
      config.vm.provider :libvirt do |libvirt|
        libvirt.vm.box_url = "http://www.krishnaraman.net/downloads/f19-libvirt.box"
      end
      
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 256]
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "#{INTNET_NAME}"]
        v.customize ["modifyvm", :id, "--nictype1", "virtio", "--nictype2", "virtio"]
        v.customize ["createhd", "--filename", "node#{i}-sdb.vmdk", "--size", 250 * 1024]
        v.customize ["createhd", "--filename", "node#{i}-sdc.vmdk", "--size", 250 * 1024]
        v.customize ["storageattach", :id, "--storagectl", "SATA", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "node#{i}-sdb.vmdk"]
        v.customize ["storageattach", :id, "--storagectl", "SATA", "--port", 2, "--device", 0, "--type", "hdd", "--medium", "node#{i}-sdc.vmdk"]
      end
      
    end
  end
  
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'site.pp'
    puppet.module_path = 'puppet/modules'
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
end
