# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
NODE_COUNT = 1

INTNET_NAME = [*('A'..'Z')].sample(8).join

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 256]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "#{INTNET_NAME}"]
    v.customize ["modifyvm", :id, "--nictype1", "virtio", "--nictype2", "virtio"]

  end


  NODE_COUNT.times do |i|
    node_id = "node#{i}".to_sym
    config.vm.define node_id  do |node|
      node.vm.box_url = "https://dl.dropboxusercontent.com/u/86066173/fedora-19.box"
      node.vm.box = "fedora19"
      node.vm.hostname = "#{node_id}.intranet.local"
    end
  end
  
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'site.pp'
    puppet.module_path = 'puppet/modules'
  end

end
